name: Saludo usando variables nomas
on:
  workflow_dispatch
env:
  DIA_DE_SEMANA : Lunes
jobs:
  saludo-variables:
    runs-on: ubuntu-latest
    env:
      SALUDO: Hola
    steps:
      - name: Saludo variables
        run: echo "$SALUDO, ${{ vars.NOMBRE }}. Hoy es $DIA_DE_SEMANA"